CREATE TABLE clientes (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    gender VARCHAR(255),
    email VARCHAR(255),
    nationality VARCHAR(255),
    name_title VARCHAR(255),
    name_first VARCHAR(255),
    name_last VARCHAR(255),
    location_region VARCHAR(255),
    location_street VARCHAR(255),
    location_city VARCHAR(255),
    location_state VARCHAR(255),
    location_postcode INT,
    location_coordinates_latitude DOUBLE,
    location_coordinates_longitude DOUBLE,
    location_timezone_offset VARCHAR(255),
    location_timezone_description VARCHAR(255),
    dob_date VARCHAR(255),
    dob_age INT,
    registered_date VARCHAR(255),
    registered_age INT,
    picture_large VARCHAR(255),
    picture_medium VARCHAR(255),
    picture_thumbnail VARCHAR(255)
);